backend:
  name: git-gateway
  branch: main

# Registramos la librería personalizada (el nombre debe coincidir con el paso 2)
media_library:
  name: r2-media

# Aunque uses R2, estos campos son requeridos por Decap
media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Noticias"
    folder: "public/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      # CAMBIO AQUÍ: de "string" a "image"
      - { label: "Imagen", name: "image", widget: "image", required: false } 
      - { label: "Contenido", name: "body", widget: "markdown" }